name: secret-gcp
run-name: secret-manager
on: [push]
jobs:
  secret-1:
    # Add "id-token" with the intended permissions.
    runs-on: ubuntu-latest
    environment: SECRET-MANAGER
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/455855396316/locations/global/workloadIdentityPools/github-cred/providers/github'
        service_account: 'secret-manager@argo-gke.iam.gserviceaccount.com'
    - name: create secret
      run: |
            gcloud config set project argo-gke
            echo "clic "| gcloud secrets create secret-2  --data-file -
