name: nodejs
on: [push]
  
jobs:
   build:
      
      runs-on: ubuntu-latest
      steps:
      
      - name: checkout repo 
        uses: actions/checkout@v2
      - name: cd 
        run: |
            cd nodejs
      - name: latest
        run: ls && pwd
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
         
      - name: run tests
        run: |
           cd nodejs 
           ls
           npm i
           npm test
    
   build-image:
     permissions:
        contents: write
        id-token: write
     runs-on: ubuntu-latest
     env:
       PROJECT_ID: argo-gke
     steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' #
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: 'gcr.io'
      - name: export image 
        run: |
            cd nodejs 
            docker build -t gcr.io/${PROJECT_ID}/gh-actions 
            docker push gcr.io/${PROJECT_ID}/gh-actions            
  
       
