name: nodejs
on: 
   push:
      paths:
      - "**.js"
jobs:
   build:
      
      runs-on: ubuntu-latest
      steps:
      
      - name: checkout repo 
        uses: actions/checkout@v2
      
      - name: list packages
        run: ls 
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm  
      - name: cd 
        run: cd nodejs
      - name: install packages
        run: npm i 
      - name: run tests
        run: npm test 
      - name: clean packages
        run: npm rm 
      
