name: nodejs
on: 
   push:
      paths:
      - "**.js"
jobs:
   build:
      
      runs-on: ubuntu-latest
      steps:
      
      - name: checkout repo 
        uses: actions/checkout@v2
      - name: cd 
        run: |
            cd nodejs
      - name: latest
        run: ls && pwd
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
         
      - name: run tests
        run: |
           cd nodejs 
           ls
           npm i
           npm test
    
      
