name: nodejs
on: 
   push:
      paths:
      - "**.js"
jobs:
   build:
      
      runs-on: self-hosted
      steps:
    
      - name: checkout repo 
        uses: actions/checkout@v2
      - name: list packages
        run: ls 
      - name: cd 
        run: cd nodejs 
      - name: install packages
        run: npm i 
      - name: run tests
        run: npm test 
      - name: clean packages
        run: npm rm 
      
