name: workflow-1 
run-name: workflow
on: [push]
jobs:
  
  
    input-job:
      runs-on: self-hosted
      outputs:
       name: ${{steps.out.outputs.name}}
       age: ${{steps.out.outputs.age}}
       greet: ${{steps.greet.outputs.greet}}
      steps:
      - name: out
        id: out
        run: |
           echo "printed" 
           echo "name=gkemhcs" > "$GITHUB_OUTPUT"
            echo "age=20" >> "$GITHUB_OUTPUT"
            echo "$GITHUB_OUTPUT"

      - name: greet
        id: greet
        run: |
            echo "name is ${{steps.out.outputs.name}} and his age is ${{steps.out.outputs.age}}" 
            echo "greet=name is ${{steps.out.outputs.name}} and his age is ${{steps.out.outputs.age}}" >> $GITHUB_OUTPUT  
    output-job:
      runs-on: self-hosted
      needs: [input-job]
      steps:
      - name: printing
        run: |
             echo  "${{toJson(needs.input-job.outputs}}"