name: workflow-1 
run-name: workflow
on: [push]
jobs:
  
  
    output-job:
      runs-on: self-hosted
      steps:
      - name: out
        run: |
           echo "printed" 
           echo "name=gkemhcs" > "$GITHUB_OUTPUT"
      - name: print
        run: |
            echo "name is ${{steps.out.outputs.name}}"