name: workflow-1 
run-name: workflow
on: [push]
jobs:
    echo-job:
      runs-on: self-hosted
      steps:
      - run: echo "welcome to  ${{github.actor}} ${{github.workspace}} ${{github.repository}}"
      - run: echo "${{toJson(github)}}"
      - run: echo "${{vars.COMPANY_NAME}}"