name: workflow-1 
run-name: workflow
on: [push]
jobs:
  
  
    output-job:
      runs-on: self-hosted
      steps:
      - name: out
        id: out
        run: |
           echo "printed" 
           echo "name=gkemhcs" > "$GITHUB_OUTPUT"
            echo "age=20" >> "$GITHUB_OUTPUT"
            echo "$GITHUB_OUTPUT"

      - name: print
        run: |
            echo "name is ${{steps.out.outputs.name}} and his age is ${{steps.out.outputs.age}}"